This notebook explains the loss function

```
loss = tf.reduce_mean(-tf.reduce_sum(y_true * tf.log(prob), reduction_indices=[1]))
```

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as imgplot
import numpy as np
import tensorflow as tf
import sys
print(sys.version_info)
print(tf.__version__)

sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
1.0.0


In [2]:
# Taken from http://stackoverflow.com/questions/29831489/numpy-1-hot-array
def convertToOneHot(vector, num_classes=None):
    result = np.zeros((len(vector), num_classes), dtype='float32')
    result[np.arange(len(vector)), vector] = 1
    return result

### Values

In [3]:
eps = 1e-8
y_true_vals = convertToOneHot((2,1,0,2),3)
prob_vals = np.asarray([[0.1,0.2,0.7],[0.9,0.1,eps],[0.95, eps, 0.05],[eps,eps,1]],dtype='float32')

### Graph

In [4]:
tf.reset_default_graph()
tf.set_random_seed(1)
#Note that we usually do not like to specify the batchsize. Choosing it `None` will leave it open
y_true = tf.placeholder(tf.float32, shape=[None, 3])
prob = tf.placeholder(tf.float32, shape=[None, 3])

### Session

In [5]:
loss = tf.reduce_mean(-tf.reduce_sum(y_true * tf.log(prob), reduction_indices=[1]))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    res = sess.run(loss, feed_dict={y_true:y_true_vals, prob:prob_vals})
res

0.67763835

### Check with numpy

In [6]:
prob_vals

array([[  1.00000001e-01,   2.00000003e-01,   6.99999988e-01],
       [  8.99999976e-01,   1.00000001e-01,   9.99999994e-09],
       [  9.49999988e-01,   9.99999994e-09,   5.00000007e-02],
       [  9.99999994e-09,   9.99999994e-09,   1.00000000e+00]], dtype=float32)

In [7]:
np.log(prob_vals)

array([[ -2.30258512,  -1.60943794,  -0.35667497],
       [ -0.10536055,  -2.30258512, -18.420681  ],
       [ -0.05129331, -18.420681  ,  -2.99573231],
       [-18.420681  , -18.420681  ,   0.        ]], dtype=float32)

In [8]:
y_true_vals * np.log(prob_vals)

array([[-0.        , -0.        , -0.35667497],
       [-0.        , -2.30258512, -0.        ],
       [-0.05129331, -0.        , -0.        ],
       [-0.        , -0.        ,  0.        ]], dtype=float32)

In [9]:
np.sum(y_true_vals * np.log(prob_vals), axis=1)

array([-0.35667497, -2.30258512, -0.05129331,  0.        ], dtype=float32)

In [10]:
np.mean(-np.sum(y_true_vals * np.log(prob_vals), axis=1))

0.67763835